spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:user_db_test;MODE=MYSQL
  h2:
    console:
      path: /h2-console
      enabled: true